# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(849, 740)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.nameLabel = QtWidgets.QLabel(self.centralwidget)
        self.nameLabel.setGeometry(QtCore.QRect(70, 120, 91, 61))
        self.nameLabel.setObjectName("nameLabel")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit.setGeometry(QtCore.QRect(180, 140, 481, 31))
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.StartTimeLabel1 = QtWidgets.QLabel(self.centralwidget)
        self.StartTimeLabel1.setGeometry(QtCore.QRect(70, 170, 101, 41))
        self.StartTimeLabel1.setObjectName("StartTimeLabel1")
        self.plainTextEdit_2 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit_2.setGeometry(QtCore.QRect(180, 180, 181, 31))
        self.plainTextEdit_2.setObjectName("plainTextEdit_2")
        self.EndTimeLabel1 = QtWidgets.QLabel(self.centralwidget)
        self.EndTimeLabel1.setGeometry(QtCore.QRect(400, 180, 91, 31))
        self.EndTimeLabel1.setObjectName("EndTimeLabel1")
        self.plainTextEdit_3 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit_3.setGeometry(QtCore.QRect(490, 180, 171, 31))
        self.plainTextEdit_3.setObjectName("plainTextEdit_3")
        self.StartTimeLabel2 = QtWidgets.QLabel(self.centralwidget)
        self.StartTimeLabel2.setGeometry(QtCore.QRect(70, 220, 111, 41))
        self.StartTimeLabel2.setObjectName("StartTimeLabel2")
        self.plainTextEdit_4 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit_4.setGeometry(QtCore.QRect(180, 230, 181, 31))
        self.plainTextEdit_4.setObjectName("plainTextEdit_4")
        self.EndTimeLabel2 = QtWidgets.QLabel(self.centralwidget)
        self.EndTimeLabel2.setGeometry(QtCore.QRect(400, 220, 91, 31))
        self.EndTimeLabel2.setObjectName("EndTimeLabel2")
        self.plainTextEdit_5 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit_5.setGeometry(QtCore.QRect(490, 220, 171, 31))
        self.plainTextEdit_5.setObjectName("plainTextEdit_5")
        self.DescriptionLabel = QtWidgets.QLabel(self.centralwidget)
        self.DescriptionLabel.setGeometry(QtCore.QRect(70, 260, 101, 41))
        self.DescriptionLabel.setObjectName("DescriptionLabel")
        self.plainTextEdit_6 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit_6.setGeometry(QtCore.QRect(180, 270, 481, 31))
        self.plainTextEdit_6.setObjectName("plainTextEdit_6")
        self.FolderLabel1 = QtWidgets.QLabel(self.centralwidget)
        self.FolderLabel1.setGeometry(QtCore.QRect(70, 320, 81, 41))
        self.FolderLabel1.setObjectName("FolderLabel1")
        self.FolderLabel2 = QtWidgets.QLabel(self.centralwidget)
        self.FolderLabel2.setGeometry(QtCore.QRect(70, 390, 101, 41))
        self.FolderLabel2.setObjectName("FolderLabel2")
        self.FolderLabel3 = QtWidgets.QLabel(self.centralwidget)
        self.FolderLabel3.setGeometry(QtCore.QRect(70, 450, 101, 41))
        self.FolderLabel3.setObjectName("FolderLabel3")
        self.plainTextEdit_7 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit_7.setGeometry(QtCore.QRect(180, 330, 481, 31))
        self.plainTextEdit_7.setObjectName("plainTextEdit_7")
        self.plainTextEdit_8 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit_8.setGeometry(QtCore.QRect(180, 390, 481, 31))
        self.plainTextEdit_8.setObjectName("plainTextEdit_8")
        self.plainTextEdit_9 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit_9.setGeometry(QtCore.QRect(180, 450, 481, 31))
        self.plainTextEdit_9.setObjectName("plainTextEdit_9")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(180, 520, 121, 41))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(360, 520, 121, 41))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(540, 520, 121, 41))
        self.pushButton_3.setObjectName("pushButton_3")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(250, 50, 581, 71))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.nameLabel.setText(_translate("MainWindow", "name"))
        self.plainTextEdit.setPlainText(_translate("MainWindow", "LSH EVENT"))
        self.StartTimeLabel1.setText(_translate("MainWindow", "Start Time"))
        self.plainTextEdit_2.setPlainText(_translate("MainWindow", "7:59 am"))
        self.EndTimeLabel1.setText(_translate("MainWindow", "End Time"))
        self.plainTextEdit_3.setPlainText(_translate("MainWindow", "7:59 am"))
        self.StartTimeLabel2.setText(_translate("MainWindow", "Start Time"))
        self.plainTextEdit_4.setPlainText(_translate("MainWindow", "7:59 am"))
        self.EndTimeLabel2.setText(_translate("MainWindow", "End Time"))
        self.plainTextEdit_5.setPlainText(_translate("MainWindow", "7:59 am"))
        self.DescriptionLabel.setText(_translate("MainWindow", "Description"))
        self.plainTextEdit_6.setPlainText(_translate("MainWindow", "White team observations"))
        self.FolderLabel1.setText(_translate("MainWindow", "Folder 1"))
        self.FolderLabel2.setText(_translate("MainWindow", "Folder 2"))
        self.FolderLabel3.setText(_translate("MainWindow", "Folder 3"))
        self.plainTextEdit_7.setPlainText(_translate("MainWindow", "path"))
        self.plainTextEdit_8.setPlainText(_translate("MainWindow", "path"))
        self.plainTextEdit_9.setPlainText(_translate("MainWindow", "path"))
        self.pushButton.setText(_translate("MainWindow", "Create Project"))
        self.pushButton_2.setText(_translate("MainWindow", "Create Vector"))
        self.pushButton_3.setText(_translate("MainWindow", "Cancel"))
        self.label_10.setText(_translate("MainWindow", "Event Configuration"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
