from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1206, 602)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.treeWidget = QtWidgets.QTreeWidget(self.centralwidget)
        self.treeWidget.setEnabled(True)
        self.treeWidget.setGeometry(QtCore.QRect(20, 50, 1161, 192))
        self.treeWidget.setAcceptDrops(False)
        self.treeWidget.setObjectName("treeWidget")
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 30, 231, 16))
        self.label.setObjectName("label")
        self.checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox.setGeometry(QtCore.QRect(950, 70, 21, 20))
        self.checkBox.setText("")
        self.checkBox.setObjectName("checkBox")
        self.checkBox_2 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_2.setGeometry(QtCore.QRect(950, 90, 20, 20))
        self.checkBox_2.setText("")
        self.checkBox_2.setObjectName("checkBox_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1206, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Nodes Configuration in Tabular Format"))
        self.treeWidget.headerItem().setText(0, _translate("MainWindow", "Node ID"))
        self.treeWidget.headerItem().setText(1, _translate("MainWindow", "Node Name"))
        self.treeWidget.headerItem().setText(2, _translate("MainWindow", "Node Timestamp"))
        self.treeWidget.headerItem().setText(3, _translate("MainWindow", "Node Description"))
        self.treeWidget.headerItem().setText(4, _translate("MainWindow", "Log Entry Reference"))
        self.treeWidget.headerItem().setText(5, _translate("MainWindow", "Log Creator"))
        self.treeWidget.headerItem().setText(6, _translate("MainWindow", "Event Type"))
        self.treeWidget.headerItem().setText(7, _translate("MainWindow", "Icon Type"))
        self.treeWidget.headerItem().setText(8, _translate("MainWindow", "Source"))
        self.treeWidget.headerItem().setText(9, _translate("MainWindow", "Node Visibility"))
        __sortingEnabled = self.treeWidget.isSortingEnabled()
        self.treeWidget.setSortingEnabled(False)
        self.treeWidget.topLevelItem(0).setText(0, _translate("MainWindow", "1"))
        self.treeWidget.topLevelItem(0).setText(1, _translate("MainWindow", "attack1"))
        self.treeWidget.topLevelItem(0).setText(2, _translate("MainWindow", "2019-10-01"))
        self.treeWidget.topLevelItem(0).setText(3, _translate("MainWindow", "Lorem ipsum dolor sit ame"))
        self.treeWidget.topLevelItem(0).setText(5, _translate("MainWindow", "Rogger Rabbit"))
        self.treeWidget.topLevelItem(0).setText(6, _translate("MainWindow", "attack"))
        self.treeWidget.topLevelItem(0).setText(7, _translate("MainWindow", "red.png"))
        self.treeWidget.topLevelItem(0).setText(8, _translate("MainWindow", "dir/logs/day1"))
        self.treeWidget.topLevelItem(1).setText(0, _translate("MainWindow", "2"))
        self.treeWidget.topLevelItem(1).setText(1, _translate("MainWindow", "attack2"))
        self.treeWidget.topLevelItem(1).setText(2, _translate("MainWindow", "2018-05-01"))
        self.treeWidget.topLevelItem(1).setText(3, _translate("MainWindow", "Vestibulum auctor dapibus neque."))
        self.treeWidget.topLevelItem(1).setText(5, _translate("MainWindow", "Rogger Rabbit"))
        self.treeWidget.topLevelItem(1).setText(6, _translate("MainWindow", "attack"))
        self.treeWidget.topLevelItem(1).setText(7, _translate("MainWindow", "blue.png"))
        self.treeWidget.topLevelItem(1).setText(8, _translate("MainWindow", "dir/logs/day2"))
        self.treeWidget.setSortingEnabled(__sortingEnabled)
        self.label.setText(_translate("Nodes Configuration in Tabular Format", "Nodes configuration in tabular format"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
