from PyQt5 import QtCore, QtGui, QtWidgets


class config_graph_formatWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(919, 667)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 10, 251, 16))
        self.label.setObjectName("label")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(30, 50, 321, 151))
        self.groupBox.setObjectName("groupBox")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(30, 100, 131, 16))
        self.label_3.setObjectName("label_3")
        self.comboBox_2 = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_2.setGeometry(QtCore.QRect(130, 100, 104, 26))
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox = QtWidgets.QComboBox(self.groupBox)
        self.comboBox.setGeometry(QtCore.QRect(160, 60, 104, 26))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(30, 60, 131, 16))
        self.label_2.setObjectName("label_2")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(30, 220, 871, 381))
        self.groupBox_2.setObjectName("groupBox_2")
        self.groupBox_3 = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox_3.setGeometry(QtCore.QRect(660, 320, 171, 51))
        self.groupBox_3.setObjectName("groupBox_3")
        self.pushButton = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton.setGeometry(QtCore.QRect(10, 20, 71, 32))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_2.setGeometry(QtCore.QRect(100, 20, 71, 32))
        self.pushButton_2.setObjectName("pushButton_2")
        self.graph = QtWidgets.QGraphicsView(self.groupBox_2)
        self.graph.setGeometry(QtCore.QRect(10, 40, 411, 281))
        self.graph.setObjectName("graph")
        self.graph_2 = QtWidgets.QGraphicsView(self.groupBox_2)
        self.graph_2.setGeometry(QtCore.QRect(440, 40, 411, 281))
        self.graph_2.setObjectName("graph_2")
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setGeometry(QtCore.QRect(180, 20, 60, 16))
        self.label_4.setObjectName("label_4")
        self.horizontalSlider = QtWidgets.QSlider(self.groupBox_2)
        self.horizontalSlider.setGeometry(QtCore.QRect(80, 350, 381, 22))
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setGeometry(QtCore.QRect(10, 350, 60, 16))
        self.label_5.setObjectName("label_5")
        self.groupBox.raise_()
        self.label.raise_()
        self.groupBox_2.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 919, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Nodes Configuration in Graphical Format"))
        self.label.setText(_translate("MainWindow", "Nodes configuration in graphical format"))
        self.groupBox.setTitle(_translate("MainWindow", "Configuration"))
        self.label_3.setText(_translate("MainWindow", "Interval units:"))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "New Item"))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "New Item"))
        self.comboBox_2.setItemText(2, _translate("MainWindow", "New Item"))
        self.comboBox_2.setItemText(3, _translate("MainWindow", "New Item"))
        self.comboBox_2.setItemText(4, _translate("MainWindow", "New Item"))
        self.comboBox.setItemText(0, _translate("MainWindow", "New Item"))
        self.comboBox.setItemText(1, _translate("MainWindow", "New Item"))
        self.comboBox.setItemText(2, _translate("MainWindow", "New Item"))
        self.comboBox.setItemText(3, _translate("MainWindow", "New Item"))
        self.comboBox.setItemText(4, _translate("MainWindow", "New Item"))
        self.label_2.setText(_translate("MainWindow", "Timeline orientation:"))
        self.groupBox_2.setTitle(_translate("MainWindow", " "))
        self.groupBox_3.setTitle(_translate("MainWindow", "Zoom"))
        self.pushButton.setText(_translate("MainWindow", "In"))
        self.pushButton_2.setText(_translate("MainWindow", "Out"))
        self.label_4.setText(_translate("MainWindow", "Interval"))
        self.label_5.setText(_translate("MainWindow", "Timeline:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = config_graph_formatWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())