# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'directoryConfiguration.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.formLayout = QtWidgets.QFormLayout(self.centralwidget)
        self.formLayout.setObjectName("formLayout")
        self.directory_configuration_label = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.directory_configuration_label.sizePolicy().hasHeightForWidth())
        self.directory_configuration_label.setSizePolicy(sizePolicy)
        self.directory_configuration_label.setObjectName("directory_configuration_label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.directory_configuration_label)
        self.root_directory_label = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.root_directory_label.sizePolicy().hasHeightForWidth())
        self.root_directory_label.setSizePolicy(sizePolicy)
        self.root_directory_label.setObjectName("root_directory_label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.root_directory_label)
        self.root_directory_text = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.root_directory_text.sizePolicy().hasHeightForWidth())
        self.root_directory_text.setSizePolicy(sizePolicy)
        self.root_directory_text.setObjectName("root_directory_text")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.SpanningRole, self.root_directory_text)
        self.red_team_folder_label = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.red_team_folder_label.sizePolicy().hasHeightForWidth())
        self.red_team_folder_label.setSizePolicy(sizePolicy)
        self.red_team_folder_label.setObjectName("red_team_folder_label")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.SpanningRole, self.red_team_folder_label)
        self.red_team_folder_text = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.red_team_folder_text.sizePolicy().hasHeightForWidth())
        self.red_team_folder_text.setSizePolicy(sizePolicy)
        self.red_team_folder_text.setObjectName("red_team_folder_text")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.SpanningRole, self.red_team_folder_text)
        self.blue_team_folder_label = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.blue_team_folder_label.sizePolicy().hasHeightForWidth())
        self.blue_team_folder_label.setSizePolicy(sizePolicy)
        self.blue_team_folder_label.setObjectName("blue_team_folder_label")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.SpanningRole, self.blue_team_folder_label)
        self.blue_team_folder_text = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.blue_team_folder_text.sizePolicy().hasHeightForWidth())
        self.blue_team_folder_text.setSizePolicy(sizePolicy)
        self.blue_team_folder_text.setObjectName("blue_team_folder_text")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.SpanningRole, self.blue_team_folder_text)
        self.white_team_folder_label = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.white_team_folder_label.sizePolicy().hasHeightForWidth())
        self.white_team_folder_label.setSizePolicy(sizePolicy)
        self.white_team_folder_label.setObjectName("white_team_folder_label")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.SpanningRole, self.white_team_folder_label)
        self.white_team_folder_text = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.white_team_folder_text.sizePolicy().hasHeightForWidth())
        self.white_team_folder_text.setSizePolicy(sizePolicy)
        self.white_team_folder_text.setObjectName("white_team_folder_text")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.SpanningRole, self.white_team_folder_text)
        self.start_data_ingestion_button = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.start_data_ingestion_button.sizePolicy().hasHeightForWidth())
        self.start_data_ingestion_button.setSizePolicy(sizePolicy)
        self.start_data_ingestion_button.setObjectName("start_data_ingestion_button")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.SpanningRole, self.start_data_ingestion_button)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 549, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.directory_configuration_label.setText(_translate("MainWindow", "Directory Configuration"))
        self.root_directory_label.setText(_translate("MainWindow", "Root Directory:"))
        self.red_team_folder_label.setText(_translate("MainWindow", "Red Team Folder:"))
        self.blue_team_folder_label.setText(_translate("MainWindow", "Blue Team Folder:"))
        self.white_team_folder_label.setText(_translate("MainWindow", "White Team Folder:"))
        self.start_data_ingestion_button.setText(_translate("MainWindow", "Start Data Ingestion"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
